### ISSUE TITLE
如何完成SakuraLoginSolver 验证？

### ISSUE THREAD

**Issue by xiaoyanlive** [KasukuSakura/mirai-login-solver-sakura#14]
服务器端：
2023-01-04 08:27:52 I/main: Auto-login 1641514221, protocol: IPAD, heartbeatStrategy: STAT_HB
请使用 SakuraLoginSolver 打开 http://<ip>:42239/request/request/11281251 来完成验证
手机SakuraLoginSolver ：
输入11281251 或http://<ip>:42239/request/request/11281251 均提示错误
哪位大佬给指教一下，谢谢！

**Comment by Karlatemp** [comment]
你的服务器ip地址呢

**Comment by d448153274** [comment]
> 你的服务器ip地址呢

感谢回复
你好，打扰一下
我也遇到了相同的问题
系统提示：请使用 SakuraLoginSolver 打开 http://<ip>:40385/request/request/37059279 来完成验证
我把IP那个换成了我自己服务器的IP，http://XX.XX.XX.XX:40385/request/request/37059279
是这样输入吗？
网页和app还是无法访问。
之前我记得好像是会出现二维码的，是我哪里操作有问题吗？

**Comment by Karlatemp** [comment]
防火墙配置 @d448153274

**Comment by d448153274** [comment]
> 防火墙配置 @d448153274

解决了感谢大佬
不过我不是关闭防火墙连接的，我的问题应该是防火墙导致的，80端口不通，但是我手机一直没办法连通我虚拟机里的linux一直没搞定
最后解决的方法是：我好死不死的在我虚拟机里的ubuntu系统登录了一下mcl，我以前一直是用ssh连接的，这次有图形界面的情况下登录mcl，运行sakura他弹出二维码选项了，可以扫码，可以验证。。。。这个问题就这样解决了
非常感谢~~~

**Comment by hisou** [comment]
请问防火墙允许所有IPv4地址访问80端口为何还是不能打开验证地址？
