### ISSUE TITLE
关于在GUI模式下, 仍希望能在控制台输出mlss所使用的端口号

### ISSUE THREAD

**Issue by TheRealKamisama** [KasukuSakura/mirai-login-solver-sakura#15]
可以更加精准的添加防火墙规则, 全局禁用防火墙对于一些服务器环境比较危险.  
或者添加可以指定端口号而不是使用随机端口号的功能.  
在0.0.1版本的时候是不是使用了中继服务器, 避免了繁琐的打洞? 为什么抛弃了这个在复杂内网环境更加容易操作的方案?

**Comment by cssxsh** [comment]
不是为了追求 `内网环境`
而是保证 `mirai-console` 和 `mirai-login-solver-sakura` 完成验证过程中 `对腾讯` 可见的公网IP一致
`内网环境` 只是低成本完成这一流程的选择

如果要使用 `中继服务器`, 那么 `中继服务器` 就要完成一并完成完整的 `Proxy` 功能，成本太高
