### ISSUE TITLE
输入地址没有 http:// 开头会报错

### ISSUE THREAD

**Issue by Superexboom** [KasukuSakura/mirai-login-solver-sakura#16]
mirai插件和手机端app皆为最新版本，服务器是Centos7，手机系统是安卓13，无任何反馈信息，无法了解报错内容

**Comment by Karlatemp** [comment]
>Q: 扫码后崩溃
>A: 更新 Android WebView, 具体方法请百度 Android 更新 WebView

**Comment by Superexboom** [comment]
否定，谷歌商店显示无更新，最后更新时间为今年的1月12日，当前版本号为109.0.5414.85，apkpure上最新的版本为109.0.5414.86

**Comment by Karlatemp** [comment]
```
G:>adb shell pidof -s com.kasukusakura.sakuraloginsolver
3264

G:>adb logcat --pid=3264
```

**Comment by Superexboom** [comment]
https://pastebin.com/WbCUDVCp

**Comment by Karlatemp** [comment]
你输入的地址是没带 `http://` 开头吗

**Comment by Superexboom** [comment]
草，大意了，日常习惯性忽略http://了，我的
