### ISSUE TITLE
报错QQ版本过低要怎么升级

### ISSUE THREAD

**Issue by yitenghao** [KasukuSakura/mirai-login-solver-sakura#20]
Login failed: Error(bot=Bot(1355958174), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点 击进入下载页面, errorInfo=)
2023-02-14 09:51:56 E/console: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1355958174), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)

**Comment by moonspring233** [comment]
同样有这个问题，请问你解决了么

**Comment by u81668899** [comment]
https://github.com/mamoe/mirai/issues/2453
据说是风控问题，切换登陆的协议可以概率解决，但本质需要设备验证（也就是二维码登陆等方式）

**Comment by FXDYJ** [comment]
删掉bots/机器人QQ号路径下的device.json文件即可

**Comment by 2764285627** [comment]
同样问题，请问怎么解决

**Comment by FXDYJ** [comment]
> 同样问题，请问怎么解决

请看如下链接内的文章：https://mirai.mamoe.net/topic/223/%E6%97%A0%E6%B3%95%E7%99%BB%E5%BD%95%E7%9A%84%E4%B8%B4%E6%97%B6%E5%A4%84%E7%90%86%E6%96%B9%E6%A1%88?_=1677761872329
