### ISSUE TITLE
打开网址后出现 .json文件不能扫码（顺便请教怎么用）

### ISSUE THREAD

**Issue by gouxianyu123** [KasukuSakura/mirai-login-solver-sakura#21]
![image](https://user-images.githubusercontent.com/96362824/218751484-fae0f9af-8b95-435e-af06-4e59dcea6645.png)
在虚拟机centos7自带的火狐打开如上
![image](https://user-images.githubusercontent.com/96362824/218751713-e351a67c-f5a0-48a7-ba6a-a1ba307132e7.png)
在windos打开edge如上，输入127.0.0.1和局域网IP一样，手机用软件打开无法访问，没有出现二维码登陆，
求问怎么弄，环境win10，mcl-consosle，把jar包直接扔插件目录了

**Comment by Karlatemp** [comment]
这个就是让你用手机访问，访问不了就是防火墙问题，自己排查
