### ISSUE TITLE
code45报错

### ISSUE THREAD

**Issue by Morax-Lizho** [KasukuSakura/mirai-login-solver-sakura#24]
E/console: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3537137590), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=)

**Comment by zwtyun** [comment]
大佬有解决方案了嘛

**Comment by MoYuNEKO** [comment]
同求解

**Comment by QxLuba** [comment]
同

**Comment by QxLuba** [comment]
大佬搞定了吗？

**Comment by MoYuNEKO** [comment]
似乎没有办法了
