### ISSUE TITLE
扫码后显示No any server availalbe

### ISSUE THREAD

**Issue by DODOTAX** [KasukuSakura/mirai-login-solver-sakura#26]
![2256F5C1C3FE25B5020C8E4368399761](https://user-images.githubusercontent.com/89824742/224475496-edb6cc72-d089-4597-812f-eec40d34a103.jpg)

**Comment by Karlatemp** [comment]
检查防火墙

**Comment by DODOTAX** [comment]
> 检查防火墙

解决了，qq版本过低了ＱＡＱ

**Comment by kartikzheng** [comment]
> > 检查防火墙
> 
> 解决了，qq版本过低了ＱＡＱ

我升级了QQ版本还是同样的错误

**Comment by DODOTAX** [comment]
> > > 检查防火墙
> > 
> > 解决了，qq版本过低了ＱＡＱ
> 
> 我升级了QQ版本还是同样的错误

不能用play版

**Comment by kartikzheng** [comment]
> > > > 检查防火墙
> > > 
> > > 
> > > 解决了，qq版本过低了ＱＡＱ
> > 
> > 
> > 我升级了QQ版本还是同样的错误
> 
> 不能用play版

用的不是play版，应用市场下的最新版本
