### ISSUE TITLE
这个APP，竟然被列入诈骗APP了！！！

### ISSUE THREAD

**Issue by q123458384** [KasukuSakura/mirai-login-solver-sakura#34]
![(V0CNG GMR}@_0~HUJWA6F](https://github.com/KasukuSakura/mirai-login-solver-sakura/assets/37495419/b8509da9-ce9c-4da1-b8d8-09ec7e49327d)
5月8号安装的，5月10号接到派出所电话，说我安装了什么诈骗平台。。。
说这个APP被反诈中心列入诈骗APP了。

另外我很好奇，派出所是怎么知道我安装了啥APP的。。

**Comment by Karlatemp** [comment]
我怎么知道，她认为是我也没办法
