### ISSUE TITLE
模拟器安装APK提示INSTALL_FAILED_INVALID_APK

### ISSUE THREAD

**Issue by Pinkuburu** [KasukuSakura/mirai-login-solver-sakura#6]
使用的mumu模拟器
![image](https://user-images.githubusercontent.com/4962790/201861332-fc8bd56a-de02-4db0-9b47-ca85941061c9.png)

**Comment by Karlatemp** [comment]
1. Require Android 9+
2. https://mirai.mamoe.net/topic/223/%E6%97%A0%E6%B3%95%E7%99%BB%E5%BD%95%E7%9A%84%E4%B8%B4%E6%97%B6%E5%A4%84%E7%90%86%E6%96%B9%E6%A1%88#:~:text=%E4%B8%8D%E8%A6%81%20%E5%B0%9D%E8%AF%95%E5%9C%A8%20Android%20%E6%A8%A1%E6%8B%9F%E5%99%A8%E4%B8%8A%E9%80%9A%E8%BF%87%E4%BB%BB%E4%BD%95%E6%96%B9%E5%BC%8F%E8%A7%A3%E5%86%B3%E9%AA%8C%E8%AF%81%E7%A0%81
