### ISSUE TITLE
OPPO A5输入后点下一步崩溃

### ISSUE THREAD

**Issue by TUSITU123** [KasukuSakura/mirai-login-solver-sakura#7]
版本：0.0.4
版本类型：Release
问题重现：
1.用OPPO A5最新ROM打开Release 0.0.4版本的APP
2.输入请求地址
3.点击下一步，崩溃
备注：希望修复！

**Comment by Karlatemp** [comment]
https://www.baidu.com/from=844b/s?word=android%20%E6%9B%B4%E6%96%B0%20webview&ts=0&t_kt=0&ie=utf-8&fm_kl=021394be2f&rsv_iqid=3856008678&rsv_t=2dc85x7kS%252Bac%252BlIRiESEommUwnVKpOEqrPbbUmSDBSuKtBQFgHXE9Gfjtg&sa=ib&ms=1&rsv_pq=3856008678&rsv_sug4=1668504523601&tj=1&ss=110&inputT=1668504524882&sugid=169267333486828

**Comment by TUSITU123** [comment]
原来是WebView的问题！
我已经通过Google Play更新了WebView，下一步就不崩溃了
建议在README里加入常见问题解答！

**Comment by TUSITU123** [comment]
对了，滑块的时候突然显示一下就只显示文字了，这是什么问题？

**Comment by TUSITU123** [comment]
难道还是WebView的问题？

**Comment by Karlatemp** [comment]
?
